### ISSUE TITLE
Add support for signing VSIX

### ISSUE THREAD

**Issue by onovotny** [onovotny/SignService#1]
Use VSIX sign tool as per https://msdn.microsoft.com/en-us/library/dd997171.aspx

**Comment by gep13** [comment]
@onovotny you mentioned that this was soon going to be supported, right?

**Comment by onovotny** [comment]
Yes.... in progress now incorporating @vcsjones' amazing work: https://github.com/vcsjones/OpenVsixSignTool

That does have a standalone exe that can be used too

**Comment by gep13** [comment]
@onovotny I believe that @MihaMarkic is already working on a Cake Addin for wrapping that tool.

**Comment by onovotny** [comment]
Done, now in master!

**Comment by gep13** [comment]
@onovotny sweet!
