### ISSUE TITLE
Run on-prem?

### ISSUE THREAD

**Issue by pvandervelde** [onovotny/SignService#11]
How much work would it be for this service to be run on-prem against an on-prem AD? I would love to use this service however we're not allowed (currently) to use Azure (or any cloud) services for our code / binaries.

**Comment by onovotny** [comment]
Technically the service would work fine, but you'd need a way to authenticate the accounts that have access to call the service.

**Comment by pvandervelde** [comment]
Would it be possible to link that to an on-prem AD. Would on-prem AD be much different from Azure AD?

**Comment by onovotny** [comment]
If you're running on-prem, then I suppose the best way would be to secure access to the service via Kerberos/NTLM group membership. There'd probably be code changes needed to support this though.

**Comment by pvandervelde** [comment]
Ok when I get to that part of our infrastructure changes I will have a look at what it takes to make that work. Would you be willing to take the changes if I put in a pull request? If not that's cool then I'll just keep a fork around somewhere. Obviously all assuming we actually get to that point :)

**Comment by onovotny** [comment]
Closing this for now; the service itself will run on-prem. Using a different auth mechanism could be an option but not one I plan on writing. I'd take a PR that would make it configurable though.
