### ISSUE TITLE
Expose as Azure Function

### ISSUE THREAD

**Issue by Aaronontheweb** [onovotny/SignService#22]
This is a great project! Is there any reason why this functionality couldn't be exposed via an Azure Function?

**Comment by onovotny** [comment]
Thanks!

It might be possible, and I had thought about that, but there's a few things that I'm using that aren't currently well-addressed by fucntions.

1. Configuration provided by Key Vault secrets. 
2. DI. This would be expensive with a function but is amortized in an api app

I'm not at all opposed to the idea if there's a good way to rearrange things.

**Comment by Aaronontheweb** [comment]
Reason I bring it up: dealing with the changing of signing certs by re-imaging a VM is a pain in the butt, so this solution as it stands offers a good architecture for eliminating that issue. But I don't need to sign stuff so often that it merits having its own virtual machine. An Azure Function would be more cost-effective for small projects.

**Comment by onovotny** [comment]
All of this can run on an Azure App Service / Website now (well, once the 2016 rollout hits your region). A B1 instance can run this.... also, the signing certs would not be on the VM anyway; it's always in an Azure Key Vault HSM now. Would that work for you? It would be a bit more than a function, but certainly less than a VM?

You can get a B1 App Service Plan for $55/mo that you can also throw however many dev websites you want (keeping in mind its small memory size) on it. Key Vault is $1/mo/cert and virtually nothing in API costs.

**Comment by Aaronontheweb** [comment]
That's probably good enough 👍

**Comment by onovotny** [comment]
Cool...I just updated the deployment docs to describe what's needed for this. Happy to assist, esp in exchange for doc updates/whatever that help others :)

**Comment by Aaronontheweb** [comment]
Thanks for the really fast response @onovotny !
