### ISSUE TITLE
Add support for excluding files with the filter flag

### ISSUE THREAD

**Issue by LBHawk** [onovotny/SignService#27]
Currently, you can only specify files to include with the filter flag.  In some situations, it would be nice to be able to specify files to exclude as well.

For Example:

To sign all files in an archive except for files in "thirdparty/" the filter text file would contain the following:

```
!**/thirdparty/**
```

To sign all dll files in "bin/" except for a couple certain .dll files:

```
**/bin/*.dll
!**/bin/ex1.dll
!**/bin/ex2.dll
```

**Comment by onovotny** [comment]
Thanks for the suggestions. I can certainly look at adding an exclude flag.

One thing is that code signing practices tend to be "conservative" with specifying what exactly should be signed, even to the point of having files spelled out explicitly. The glob was an attempt to make that a bit easier.

**Comment by LBHawk** [comment]
Gotcha, I've submitted PR #28 which adds support for this if you decide it's an addition you would like.

**Comment by onovotny** [comment]
In this case, doesn't seem too bad, I would just be cautions about using globs (inclusive or exclusive). That said, the service won't stop you from shooting yourself in the foot ;)

**Comment by onovotny** [comment]
Thanks for the PR!
