### ISSUE TITLE
Debug: SignService-created user "not found in directory" error in AD when using SignClient

### ISSUE THREAD

**Issue by Aaronontheweb** [onovotny/SignService#57]
I think this question mostly has to do with my lack of familiarity with Azure AD, but just in case I configured something wrong I'd like to get a sanity check.

Received the following error message when using the latest `SignClient` global tool via NuGet:

```
AADSTS50034: The user account does not exist in the [redacted] directory. To sign into this application, the account must be added to the directory.
```

I created a user, "Bob" via the steps outlined in the [Administration guide](https://github.com/onovotny/SignService/blob/master/docs/Administration.md), added a cert to the vault and then marked the user as "Configured" to use SignService once I had my certificate configured correctly.

I then added an `appsettings.json` file with the following values:

```
{
  "SignClient": {
    "AzureAd": {
      "AADInstance": "https://login.microsoftonline.com/",
      "ClientId": "[SignService Client ClientId]",
      "TenantId": "[TenantId shared by client and server app]"
    },
    "Service": {
      "Url": "[Uri of website created by ARM template]",
      "ResourceId": "[Resource Id for SignService Server/Client]"
    }
  }
}
```

I then ran the global tool with the following parameters:

```
signclient sign --config appsettings.json -i MyDll.dll -r "Bob" -s "randomly generated password" -n 'MyDll' -d 'MyDll' -u 'https://github.com/Aaronontheweb/MyDLL'
```

What would cause this "user not found in directory [tenant ID]" error to get raised with this configuration? Am I using some of the values that were supplied by the `InstallUtility` incorrectly?

**Comment by onovotny** [comment]
When you created the user, what is the full username? It would default to the default domain of the tenant.

Are you using just "Bob" as the -r parameter or "bob@thetenant.onmicrosoft.com" (or whatever the default/primary domain suffix is)?

**Comment by Aaronontheweb** [comment]
Ah, I was using just bob and bob@my domain.com - so it needs to be bob@my domain.onmicrosoft.com ?

**Comment by onovotny** [comment]
Yes, that's right. By default, if you don't enter in the @ suffix in the new-user screen, it defaults to the tenant default.

**Comment by Aaronontheweb** [comment]
I got this working - so funnily enough, looks like it was a caching issue with AD. Users I created via the SignService server worked, but only if I tried logging in with them a few hours later - not moments later like I was doing when I filed this issue. I'm not sure why that would be the case, but that's what resolved it for me.
