### ISSUE TITLE
Add Timeout to WaitForExit.

### ISSUE THREAD

**Issue by vcsjones** [onovotny/SignService#8]
On this line:

https://github.com/onovotny/SignService/blob/63f6c20c91a3b9cfe48e4a05cb85a19a5d76ed42/src/SignService/SigntoolCodeSignService.cs#L77

`WaitForExit` will wait indefinitely. I would instead use the [overload](https://msdn.microsoft.com/en-us/library/ty0d8k56(v=vs.110).aspx) that accepts a timeout to prevent it from getting hung forever. This is possible if `signtool` is trying to ask for user input. Something like this:

```
if (!signtool.WaitForExit(30 * 1000))
{
    signtool.Kill();
    //handle error.
}
```

This should be done for both the SHA1 and SHA256 signature processes.

**Comment by onovotny** [comment]
Fixed, thanks!
