### ISSUE TITLE
Configuration of dual signatures

### ISSUE THREAD

**Issue by vcsjones** [onovotny/SignService#9]
Sometimes it is desirable to skip the dual signature of SHA1/SHA256 and do SHA256 only. Some cases:

* Dual signatures are not recognized in Windows 7 and below on MSIs. The correct "fix" for this is to package the MSI in an EXE, however this isn't feasible if the intention of the MSI is to be distributed by Group Policy.

* The extra signature and counter signatures adds a few hundred bytes to the final executable's size. For platforms that are very mindful of binary size (IoT), this might be unacceptable. Therefore the SHA1 signature is omitted.

The default behavior of doing both a SHA1 and a SHA256 is good, but an option should be available for SHA256-only signing.

To do this, the SHA1 step should go away, then the `/as` option should be removed in the SHA256 line (since we aren't appending a signature anymore).

**Comment by onovotny** [comment]
sure -- the one thing is that I need to make a proper command line parser first #3. The current command lines are way too brittle, so even adding a switch like this would be painful.

**Comment by onovotny** [comment]
Any ideas? I was thinking of @terajobt's system.commandline in corefxlab

**Comment by vcsjones** [comment]
Hm, usually I've rolled my own in most cases (because it's fun). What's Kestrel using?

**Comment by onovotny** [comment]
done, thanks!
